# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.19a1.dev1+g3796a1c2.d20221206'
__version_tuple__ = version_tuple = (0, 19, 'dev1', 'g3796a1c2.d20221206')
