name: lstio
channels:
  - conda-forge
  - default
dependencies:
  - astropy
  - python>=3.8
  - ctapipe>=0.15
  - eventio
  - corsikaio
  - protozfits=2.0
  - zeromq
  - ipython
  - numba
  - numpy>=1.18
  - numpydoc
  - pytest
  - pyyaml
  - zlib
  - pip
  - h5py
