import numpy as np


N_GAINS = 2
N_MODULES = 265
N_PIXELS_MODULE = 7
N_PIXELS = N_MODULES * N_PIXELS_MODULE
N_CAPACITORS_CHANNEL = 1024
# 4 drs4 channels are cascaded for each pixel
N_CAPACITORS_PIXEL = 4 * N_CAPACITORS_CHANNEL
N_SAMPLES = 40
HIGH_GAIN = 0
LOW_GAIN = 1
LAST_RUN_WITH_OLD_FIRMWARE = 1574
CLOCK_FREQUENCY_KHZ = 133e3

# we have 8 channels per module, but only 7 are used.
N_CHANNELS_MODULE = 8

# First capacitor order according Dragon v5 board data format
CHANNEL_ORDER_HIGH_GAIN = [0, 0, 1, 1, 2, 2, 3]
CHANNEL_ORDER_LOW_GAIN = [4, 4, 5, 5, 6, 6, 7]

# on which module is a pixel?
MODULE_INDEX = np.repeat(np.arange(N_MODULES), 7)

CHANNEL_INDEX_LOW_GAIN = MODULE_INDEX * N_CHANNELS_MODULE + np.tile(CHANNEL_ORDER_LOW_GAIN, N_MODULES)
CHANNEL_INDEX_HIGH_GAIN = MODULE_INDEX * N_CHANNELS_MODULE + np.tile(CHANNEL_ORDER_HIGH_GAIN, N_MODULES)
