name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # Daily at 02:00 UTC

env:
  NUMBA_NUM_THREADS: 1
  MPLBACKEND: Agg
  PYTEST_ADDOPTS: --color=yes

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.12"
            ctapipe-version: "0.23.2"
          - python-version: "3.12"
            ctapipe-version: "0.24.0"
          - python-version: "3.13"
            ctapipe-version: "0.25.0"
          - python-version: "3.12"
            ctapipe-version: "0.26.0"
          - python-version: "3.13"
            ctapipe-version: "latest"
          - python-version: "3.13"
            ctapipe-version: "nightly"
    continue-on-error: ${{ matrix.ctapipe-version == 'nightly' }}

    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set python version
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          sed -i -e "s/- python=.*/- python=$PYTHON_VERSION/g" environment.yml

      - name: Create and activate env
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          environment-name: lstio
          init-shell: bash
          cache-downloads: true

      - name: Install
        env:
          CTAPIPE_VERSION: ${{ matrix.ctapipe-version }}
        run: |
          pip install -e .
          if [[ "$CTAPIPE_VERSION" == "latest" ]]; then
            pip install pytest-cov ctapipe ${{ matrix.extra-reqs }}
          elif [[ "$CTAPIPE_VERSION" == "nightly" ]]; then
            pip install pytest-cov "ctapipe@git+https://github.com/cta-observatory/ctapipe.git@main" ${{ matrix.extra-reqs }}
          else
            pip install pytest-cov "ctapipe==$CTAPIPE_VERSION" ${{ matrix.extra-reqs }}
          fi
          ctapipe-info --version
          git describe --tags

      - name: Test Plugin
        run: |
          # check the LSTEventSource is available for LST
          python eventsource_subclasses.py | grep LSTEventSource

      - name: Download test data
        env:
          TEST_DATA_USER: ${{ secrets.test_data_user }}
          TEST_DATA_PASSWORD: ${{ secrets.test_data_password }}
        run: |
          ./download_test_data.sh

      - name: Tests
        run: |
          pytest --cov=ctapipe_io_lst --cov-report=xml

      - uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
